name: deepbreath
description: "A Flutter project that measures tha quality of the air based on a location"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  geolocator: ^11.0.0
  get: ^4.6.6
  http: ^1.2.0
  flag: ^7.0.0
  hero_animation: ^1.1.4
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: ProximaNova
      fonts:
        - asset: fonts/Mark Simonson  Proxima Nova Regular.otf
        - asset: fonts/Mark Simonson  Proxima Nova Regular Italic.otf
          style: italic
  uses-material-design: true

